/* */
#ifndef _PIOS_BOARD_H_
#define _PIOS_BOARD_H_

typedef enum {
    PIOS_BOARD_RECEIVER_PIN3,
    PIOS_BOARD_RECEIVER_PIN4,
    PIOS_BOARD_RECEIVER_PIN5,
    PIOS_BOARD_RECEIVER_PIN6,
    PIOS_BOARD_RECEIVER_PIN7,
    PIOS_BOARD_RECEIVER_PIN8,

    PIOS_BOARD_SERVO_PIN1,
    PIOS_BOARD_SERVO_PIN2,
    PIOS_BOARD_SERVO_PIN3,
    PIOS_BOARD_SERVO_PIN4,
    PIOS_BOARD_SERVO_PIN5,
    PIOS_BOARD_SERVO_PIN6,

    PIOS_BOARD_MAIN_PIN3,
    PIOS_BOARD_MAIN_PIN4,
    
    PIOS_BOARD_FLEXI_PIN3,
    PIOS_BOARD_FLEXI_PIN4,

    PIOS_BOARD_SWD_PIN3, /* some boards do not have swd connector */
    PIOS_BOARD_SWD_PIN4, /* some boards do not have swd connector */
    
    /* aliases */
    PIOS_BOARD_MAIN_RX   = PIOS_BOARD_MAIN_PIN4,
    PIOS_BOARD_MAIN_TX   = PIOS_BOARD_MAIN_PIN3,
    
    PIOS_BOARD_FLEXI_RX  = PIOS_BOARD_FLEXI_PIN4,
    PIOS_BOARD_FLEXI_TX  = PIOS_BOARD_FLEXI_PIN3,
    
    PIOS_BOARD_FLEXI_SDA = PIOS_BOARD_FLEXI_PIN4,
    PIOS_BOARD_FLEXI_SCK = PIOS_BOARD_FLEXI_PIN3,
    
    PIOS_BOARD_FLEXI_PPM = PIOS_BOARD_FLEXI_PIN4,
    
    PIOS_BOARD_RECEIVER_PPM  = PIOS_BOARD_RECEIVER_PIN3,
    PIOS_BOARD_RECEIVER_PPM8 = PIOS_BOARD_RECEIVER_PIN8,
    
    PIOS_BOARD_RECEIVER_PWM1 = PIOS_BOARD_RECEIVER_PIN3,
    PIOS_BOARD_RECEIVER_PWM2 = PIOS_BOARD_RECEIVER_PIN4,
    PIOS_BOARD_RECEIVER_PWM3 = PIOS_BOARD_RECEIVER_PIN5,
    PIOS_BOARD_RECEIVER_PWM4 = PIOS_BOARD_RECEIVER_PIN6,
    PIOS_BOARD_RECEIVER_PWM5 = PIOS_BOARD_RECEIVER_PIN7,
    PIOS_BOARD_RECEIVER_PWM6 = PIOS_BOARD_RECEIVER_PIN8,

} pios_board_pin_id_t;

#endif /* _PIOS_BOARD_H_ */
